### ISSUE TITLE
generated-test-sources for FilterRequest_inline in GenSpringGatewayHttpHeadersFilterAdvice has error

### ISSUE THREAD

**Issue by jxd134** [megaease/easeagent#108]
![图片](https://user-images.githubusercontent.com/14814212/131608819-ca8f6733-fab6-4fa5-a002-64b981d50dca.png)

**Comment by akwei** [comment]
I  can not found any error after cleaning and rebuild.
![image](https://user-images.githubusercontent.com/765991/131633038-91ab924f-fd2c-483b-a55b-d5c2b27b32b6.png)

**Comment by jxd134** [comment]
![图片](https://user-images.githubusercontent.com/14814212/131633644-c8d784f4-c11f-447d-81f0-f026cc0c2137.png)
I just right click run on module `sniffer` for test in idea, occurs the erroe as below:
![图片](https://user-images.githubusercontent.com/14814212/131633944-9edd7321-391f-4954-aabe-f20a5387e44d.png)

What steps do I need to perform to run the test for module `sniffer`?
