### ISSUE TITLE
More comments request

### ISSUE THREAD

**Issue by Michael-crazyman** [megaease/easeagent#135]
I am wondering is it possible that we can add more comments and explanations for some critical components so that we can understand the purpose clearer?
As a freshman in the Java Agent area, I'd like to learn something from this project, but it is a bit hard for me to follow the code and design.

**Comment by akwei** [comment]
We have one video to introduce the EaseAgent
https://www.youtube.com/watch?v=LNc9LLSvF0E&t=29s
or 
https://www.bilibili.com/video/BV1eh41167Lx

EaseAgent uses a lot of Byte-Buddy features, you can also learn about Byte-Buddy。

**Comment by akwei** [comment]
You can join our slack :

**Comment by akwei** [comment]
You can join our slack:
https://join.slack.com/t/openmegaease/shared_invite/zt-upo7v306-lYPHvVwKnvwlqR0Zl2vveA
