### ISSUE TITLE
Notes on the different configurations of the new and old versions of easeagent

### ISSUE THREAD

**Issue by observeralone** [megaease/easeagent#140]
# background:
Starting from 2.0.0, easeagent will use plug-in solutions for monitoring. With the application of the plug-in solution, the configuration rules have also changed.
The old rules are configured as follows:
```yaml
observability.metrics.enabled=true
# metrics access
observability.metrics.access.enabled=true
observability.metrics.access.interval=30
observability.metrics.access.topic=application-log
observability.metrics.access.appendType=kafka
```
The new rule configuration is as follows:
```yaml
plugin.observability.global.metric.enabled=true
plugin.observability.access.metric.enabled=true
plugin.observability.access.metric.interval=30
plugin.observability.access.metric.topic=application-log
plugin.observability.access.metric.appendType=kafka
```

The migration of plugin will cause the old configuration to become invalid. 
Since there are other control systems that use api to modify the configuration, it is not friendly to discard it directly.

# action
We decided to be compatible with the old version of the api configuration interface, modify the configuration monitored by the api, and convert it to the new version of the configuration through rules.
`observability.metrics.enabled to plugin.observability.global.metric.enabled`
For new configurations in the future, please use the new version of the configuration rules.

**Comment by Oseenix** [comment]
finished
