### ISSUE TITLE
Support Yaml format configuration file

### ISSUE THREAD

**Issue by Oseenix** [megaease/easeagent#141]
support YAML format configuration file in future

**Comment by HessTina-YuI** [comment]
If both exist agent.propertis and agent.yml, loading which one.

**Comment by Oseenix** [comment]
There are two Configuration files now, the default one is packaged in easeagent-dep.jar which contains default configuration, the other one is the user specifies by -Deaseagent.conf.path, which has a higher priority and will override default configuration. So, if both exist, the higher priority override the other one, and if we support yaml, maybe we only left the yaml file as default configuration file.

**Comment by HessTina-YuI** [comment]
Ok, I get what you meant now. Is this function complete? I want to this.

**Comment by Oseenix** [comment]
> Ok, I get what you meant now. Is this function complete? I want to this.

Great! this function has not started yet. maybe we can set up an online meeting and give a brief overview of what's going on?

**Comment by HessTina-YuI** [comment]
Yeah! My wechat is HessTina-YuI.

**Comment by Oseenix** [comment]
> Yeah! My wechat is HessTina-YuI.

I search the id, and it shows that the user has not found, do you mind add my id: zhou_jinze

**Comment by Oseenix** [comment]
support by #255
