### ISSUE TITLE
Export OpenTelemetry format tracing data to Opentelemetry collector

### ISSUE THREAD

**Issue by Oseenix** [megaease/easeagent#260]
**Is your feature request related to a problem? Please describe.**
Opentelemetry reporter, exporting OpenTelemetry format tracing data.
reference [opentelemetry-to-zipkin](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/zipkin.md)

**Describe the solution you'd like**
- Implement an [Encoder](https://github.com/megaease/easeagent/blob/master/plugin-api/src/main/java/com/megaease/easeagent/plugin/report/Encoder.java) to achieve the transformation of Zipkin format to Opentelmetry format. 
- Add a GRPCSender to send encoded Opentelemetry Span data to Opentelemetry collector.

**Describe alternatives you've considered**
NA
 
**Additional context**

---
Thanks for contributing 🎉!

**Comment by HessTina-YuI** [comment]
I want to do it.

**Comment by observeralone** [comment]
Discuss the results: The [opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-collector) is native support zipkin's data format. [opentelemetry receivers](https://opentelemetry.io/docs/collector/configuration/#receivers) configure the zikpin data source.

I'm going to close it
