### ISSUE TITLE
Create Custom Logger to prevent conflict with user's application

### ISSUE THREAD

**Issue by akwei** [megaease/easeagent#44]
The agent's log configuration conflicts with the user's application.

Easeagent use log4j to solve 2 things:
* Output log info to easeaget.log
* Send metrics information to kafka.

### In tomcat
The internal logging for Apache Tomcat uses JULI, a packaged renamed fork of Apache Commons Logging that is hard-coded to use the java.util.logging framework. This ensures that Tomcat's internal logging and any web application logging will remain independent, even if a web application uses Apache Commons Logging.

Reference: https://tomcat.apache.org/tomcat-9.0-doc/logging.html

### In pinpoint and skywalking
Pinoint and skywalking create custom Logger class. They use sender class to transfer trace and metric to collector server.

### EaseAgent Solution
We should create custom logger class for logging agent info to prevent conflict with user's application. And create sender class for send metric information.

Reference:
* [pinpoint BootLogger](https://github.com/pinpoint-apm/pinpoint/blob/master/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/BootLogger.java)
* [skywalking ILog](https://github.com/apache/skywalking/blob/master/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/logging/api/ILog.java)

**Comment by akwei** [comment]
The problem is not solved.

**Comment by Oseenix** [comment]
when the user's application use the log4j2, it would find the configuration file 'log4j2.xml' in the classpath. The agent jar is included in the classpath with the log4j2.xml file, so it may be found and use by the user's application. 
So the solution can be simple: change the configuration file name in the agent jar.
