### ISSUE TITLE
Add  a Simple tracing  view UI

### ISSUE THREAD

**Issue by qdongxu** [megaease/easeagent#89]
The quick start employs [Promethues](https://prometheus.io) to view the effect of metrics. But there are no recommendations to view the effect of tracing. 

Propose to add a simple web server, composed of only one source file, to show the tracing in YAML. This server is required only to collect and aggregate the trace in memory for the evaluation of `easeagent`.   easeagent output tracing to the server directly without any broker. It's deliberately to show in YAML format because a product-level tracing viewer connects many facts and too heavy to deploy for a quick start evaluation.

**Comment by akwei** [comment]
I will output trace info to [Zipkin](https://zipkin.io/)

**Comment by akwei** [comment]
> hello , How is it now about UI.

It is in my roadmap and  has not yet started development

**Comment by akwei** [comment]
EaseAgent already supports sending tracing data to Zipkin Server. 
This is PR https://github.com/megaease/easeagent/pull/103
